//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DONVI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DONVI()
        {
            this.tb_CHUNGTU = new HashSet<tb_CHUNGTU>();
            this.tb_SYS_USER = new HashSet<tb_SYS_USER>();
        }
    
        public string MADV { get; set; }
        public string TENDVI { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string MACTY { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public Nullable<bool> KHO { get; set; }
        public string KYHIEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHUNGTU> tb_CHUNGTU { get; set; }
        public virtual tb_CONGTY tb_CONGTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SYS_USER> tb_SYS_USER { get; set; }
    }
}
