//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HANGHOA()
        {
            this.tb_CHUNGTU_CT = new HashSet<tb_CHUNGTU_CT>();
            this.tb_TONKHO = new HashSet<tb_TONKHO>();
        }
    
        public string BARCODE { get; set; }
        public string TENHH { get; set; }
        public string TENTAT { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string MANCC { get; set; }
        public Nullable<int> MAXX { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> IDNHOM { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<bool> DISABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHUNGTU_CT> tb_CHUNGTU_CT { get; set; }
        public virtual tb_DVT tb_DVT { get; set; }
        public virtual tb_NHACUNGCAP tb_NHACUNGCAP { get; set; }
        public virtual tb_NHOMHH tb_NHOMHH { get; set; }
        public virtual tb_XUATXU tb_XUATXU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TONKHO> tb_TONKHO { get; set; }
    }
}
