//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SYS_REPORT()
        {
            this.tb_SYS_RIGHT_REP = new HashSet<tb_SYS_RIGHT_REP>();
        }
    
        public int REP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REP_NAME { get; set; }
        public Nullable<bool> VISIBLED { get; set; }
        public Nullable<bool> TUNGAY { get; set; }
        public Nullable<bool> THANGNAM { get; set; }
        public Nullable<bool> MACTY { get; set; }
        public Nullable<bool> MADVI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SYS_RIGHT_REP> tb_SYS_RIGHT_REP { get; set; }
    }
}
